### ISSUE TITLE
List resetting every time I leave the app

### ISSUE THREAD

**Issue by YossiDoe** [RigidasSoftware/rigi-docs#1]
This could've been a good app. Sadly it doesn't deliver. 

If you leave the app (before finishing picking all products) then reopen the app, the whole previous pick list disappears and you will only see a list of products that have been sold since you last logged out, meaning that all products that have not been picked yet before closing the app will never be picked.

Is there a solution to this?

**Comment by mike-eason** [comment]
It sounds like you're issue is related to ePickList. I would recommend raising a support ticket [here](https://rigidassoftware.co.uk/#contact).
