### ISSUE TITLE
Epicklist error, token required

### ISSUE THREAD

**Issue by lowcostmetal** [RigidasSoftware/rigi-docs#2]
We are not able to connect to picklist this morning and Rigidas website is greyed out not allowing us to contact.
We have tried resetting everything but still cannot connect.
Shows as disconnected in linwworks app screen also.

Getting error token must be provided (Linnworks Token)

**Comment by mike-eason** [comment]
Hello there,

If you're still having issues with this, please contact the support team directly [here](https://rigidassoftware.co.uk/#contact).
