### ISSUE TITLE
Un authorised account 

### ISSUE THREAD

**Issue by Jo-iso77** [RigidasSoftware/rigi-docs#5]
Hello I signed up for the free trial for 7 days on friday last week and i'm unable gain access, the device is saying unauthorized access. I have registered the account but still no luck.
I have a new zebra TC21 which was recommend by yourselves 
Regards Jo

**Comment by mike-eason** [comment]
Hello Jo,

GitHub probably isn't the place to resolve your issue. Please raise a support ticket instead.

**Comment by Jo-iso77** [comment]
Hi Mike,
This is where the support ticket lead me too.

Kind Regards Joanne Ison

Posh Porschey
Unit 7 & 8 Vulcan Place, 
Worksop
Notts 
S80 1RN
Telephone Number 07773082082

**Comment by mike-eason** [comment]
Hi Jo, I no longer work for Rigidas, I really can't help you. Please contact support directly.
